### ISSUE TITLE
When a revision is checked out, set trashed to false

### ISSUE THREAD

**Issue by elbotho** [serlo/serlo.org-database-layer#102]
Currently trashed revisions can be checked out but are still trashed afterwards.
(related #100)

Note: This is probably a change from the legacy behaviour. The UI used to only offer the option to "restore" a rejected revision. I simplified this in the frontend to allow a checkout for all revisions.
If this is undesired for some reason, please tell me :)

**Comment by kulla** [comment]
Bug is in API (the update method for the cache was missing). See https://github.com/serlo/api.serlo.org/pull/405
