### ISSUE TITLE
CreateCommentNotificationEvent breaks notifications query

### ISSUE THREAD

**Issue by elbotho** [serlo/serlo.org-database-layer#119]
With `Invalid value received from data source`.

Sentry: https://sentry.io/organizations/serlo/issues/2481072554/?environment=staging&project=5385534&query=is%3Aunresolved

Basically uuid `192412` is expected to be a comment but is a solution.

Discovered with the `notifications` query of user `Mathewally` (unread notifs) but I narrowed it down to:
_Minimal query to run into error_
``` gql
{
  notificationEvent(id:413198){
    ... on CreateCommentNotificationEvent{      
      comment{id}
    }
  }
}
```

My theory is that the comments id and objects id are mixed up somewhere in api or db layer.

**Comment by elbotho** [comment]
Gotcha! (maybe)

Answer of the db-layer:
``` json
{
  "__typename":"CreateCommentNotificationEvent",
  "id":413198,
  "instance":"de",
  "date":"2021-06-29T14:19:10+02:00",
  "actorId":216530,
  "objectId":192412, <-
  "threadId":217154, 
  "commentId":192412 <-
}
```

**Comment by elbotho** [comment]
@inyono could you stare with me at this line for a moment? :)
https://github.com/serlo/serlo.org-database-layer/blob/main/src/event/model/create_comment.rs#L22

**Comment by elbotho** [comment]
I mean the Comment is the object of the NotificationEvent, right?
So could this be an API bug after all?  (maybe decoder? have not looked into those so far…)

**Comment by inyono** [comment]
The duplication is okay and intended. Question is whether objectId is indeed the comment (or instead the object commented on). Would need to check legacy for that.

**Comment by elbotho** [comment]
Ah sorry, but commentId def. should not point to the content uuid. That can't be right?

**Comment by elbotho** [comment]
I don't see where the content uuid could end up in place of  `objectId` and `commentId`. To my understanding both legacy and db-layer should use the comments id.

**Comment by elbotho** [comment]
Legacy Code:
``` php
            case 'discussion/comment/create':
                return [
                    '__typename' => 'CreateCommentNotificationEvent',
                    'actorId' => $event->getActor()->getId(),
                    'threadId' => $event->getParameter('discussion')->getId(),
                    'commentId' => $event->getObject()->getId(),
                ];
            case 'discussion/create':
                return [
                    '__typename' => 'CreateThreadNotificationEvent',
                    'actorId' => $event->getActor()->getId(),
                    'threadId' => $event->getObject()->getId(),
                    'objectId' => $event->getParameter('on')->getId(),
                ];
```

**Comment by kulla** [comment]
Okay, I have looked into the issue: There are 13 events with a wrong object_id attached to it...

**Comment by elbotho** [comment]
> Okay, I have looked into the issue: There are 13 events with a wrong object_id attached to it...

this means we have to fix those manually in the db or delete them, right?

**Comment by kulla** [comment]
> this means we have to fix those manually in the db or delete them, right?

Right. Want to push the fix in production before though...

**Comment by kulla** [comment]
@elbotho I just corrected the values in production / staging. https://nbviewer.jupyter.org/github/kulla/serlo-evaluations/blob/eddc968b150349914f685662bf653072932ec9c9/2021/2021-07-08%20Fix%20SQL%20after%20bug.ipynb documents what I have done. Can you check whether everything is fine now?

**Comment by elbotho** [comment]
@kulla thank you!
The accounts with broken notifs I knew of work again.
So far so good :)
