### ISSUE TITLE
Shall IRIs start with http or https?

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org-database-layer#163]
What is the best practise for IRIs? Shall we have `https://serlo.org/1495` or `http://serlo.org/1495`?

**Comment by inyono** [comment]
IMHO: https since http links just look wrong in my opinion ;) From my quick research, both approaches are fine and used, so 🤷‍♂️

**Comment by kulla** [comment]
I have started a question on SO about this: https://stackoverflow.com/questions/70403827/iris-shall-http-or-https-be-used ...

**Comment by kulla** [comment]
https://stackoverflow.com/a/70404017/1165155 -> we are fine with `https`
