### ISSUE TITLE
Add*Revision time difference

### ISSUE THREAD

**Issue by elbotho** [serlo/serlo.org-database-layer#204]
I investigated the `-2h` bug further. 
It's definitely not a frontend problem. (ping @hugotiburtino)

When I save a revision with the new endpoint and the another one with the legacy endpoint at roughly the same time the datestings returned by the API is 2h off.

Query:
``` gql
{
  uuid(id: 243006) {
  	... on ArticleRevision {
      date
    }
  }
}
```

Returned datestring (saved with legacy endpoint) `"2022-04-08T08:52:26+02:00"` (correct)
Returned datestring (saved with new endpoint) "2022-04-08T06:51:46+02:00" ( -2h )

**Comment by inyono** [comment]
I think we should fix that (for compatibility with legacy and to keep it consistent until we remove legacy at some point). The revisions that have already been created with the time difference are fine, though, no need to try to fix them in any way.

**Comment by kulla** [comment]
Fix got merged in `main` with https://github.com/serlo/serlo.org-database-layer/commit/b22d1e6820a6050900f6c22c713d2e47e0627ba1

**Comment by elbotho** [comment]
Could you ping me in when this is deployed? Thanks!
