### ISSUE TITLE
TaxonomyDeleteEntityLinkMutation

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org-database-layer#211]
### Message (TypeScript definition)

```ts
interface Message {
  type: "TaxonomyDeleteEntityLinkMutation",
  payload: Payload
}

interface Payload {
  entityIds: number[]
  taxonomyTermId: number
}
```
### Output (TypeScript definition)

```ts
interface Output {
  success: boolean
}
```

## Description what happens in the database layer

Deletes a link in the table `term_taxonomy_entity`.

## Necessary checks / possible errors

- [x] `entityIds` belong each to an entity
- [x] `taxonomyTermId` belongs to a taxonomy term
- [x] there is a link between them
- [x] Create necessary events

**Comment by hugotiburtino** [comment]
> - [ ] entityIds belong each to an entity  
> - [ ] taxonomyTermId belongs to a taxonomy term
  
I'm not sure if we need these checks (at least not as extra verifications), since if the ids are already in the table they exist and belong to entities and taxonomies.

**Comment by hugotiburtino** [comment]
Do you think we need to reorder the positions of the remaining linked entities? Let's say, if we have the folllowing table
```
+-----+-----------+------------------+----------+
| id  | entity_id | term_taxonomy_id | position |
+-----+-----------+------------------+----------+
| 319 |      2131 |                7 |        1 |
| 345 |      2183 |                7 |        2 |
| 346 |      2185 |                7 |        3 |
+-----+-----------+------------------+----------+
```
And we delete 345. Should the table stay like that (ugly, but doesn't actually matter)
```
+-----+-----------+------------------+----------+
| id  | entity_id | term_taxonomy_id | position |
+-----+-----------+------------------+----------+
| 319 |      2131 |                7 |        1 |
| 346 |      2185 |                7 |        3 |
+-----+-----------+------------------+----------+
```
Or like that (pretty, but it would need more code for something maybe useless) :
```
+-----+-----------+------------------+----------+
| id  | entity_id | term_taxonomy_id | position |
+-----+-----------+------------------+----------+
| 319 |      2131 |                7 |        1 |
| 346 |      2185 |                7 |        2 |
+-----+-----------+------------------+----------+
```

**Comment by kulla** [comment]
> Do you think we need to reorder the positions of the remaining linked entities?

Not necessary

**Comment by kulla** [comment]
@hugotiburtino With "there is a link between them" you already have tested " `entityIds` belong each to an entity" and "`taxonomyTermId` belongs to a taxonomy term" -> just add tests for both cases

**Comment by kulla** [comment]
Closed in https://github.com/serlo/serlo.org-database-layer/pull/222
