### ISSUE TITLE
TaxonomySortMutation

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org-database-layer#214]
### Message (TypeScript definition)

```ts
interface Message {
  type: "TaxonomySortMutation",
  payload: Payload
}

interface Payload {
  childrenIds: number[]
  taxonomyTermId: number
  userId: number
}
```
### Output (TypeScript definition)

```ts
interface Output {
  success: boolean
}
```

## Description what happens in the database layer

Sets the position of the linked entities in taxonomy term with `taxonomyTermId` according to `childrenIds` + position of children taxonomy ids. The position of the linked entities / taxonomy elements can be the index in `childrenIds`.

## Necessary checks / possible errors

- [x] `childrenIds` is the same set of uuids as the union of entities linked to `taxonomyTermId` and the taxonomy term children of `taxonomyTermId`

**Comment by hugotiburtino** [comment]
- [ ] Add constraints to the `term_taxonomy_entity`. Right now (at least in the dump), it doesn't check if  `entity_id` and `term_taxonomy_id` have their counterparts in the respective tables.

**Comment by hugotiburtino** [comment]
Hey @kulla 
just to be sure: it doesn't trigger any event, does it? Not even taxonomy/term/update?

**Comment by kulla** [comment]
> just to be sure: it doesn't trigger any event, does it? Not even taxonomy/term/update?
> If it doesn't we don't need userId in payload.

Do a "taxonomy/term/update" for the root taxonomy
