### ISSUE TITLE
[New Endpoint] EntitySetLicenseMutation

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org-database-layer#224]
### Message (TypeScript definition)

```ts
interface Message {
  type: 'EntitySetLicenseMutation'
  payload: Payload
}

interface Payload {
  entityId: number!
  licenseId: number!
  userId: number!
}
```

### Output (TypeScript definition)

```ts
interface Output {
  success: boolean
}
```

## Description what happens in the database layer

Sets the license of entity with id `entityId` to `licenseId`

## Necessary checks / possible errors

- [ ] Does entity with license `entityId` exist?
- [x] Create SetLicense event

**Comment by hugotiburtino** [comment]
Some TODOS: 
- [ ] Remove/drop from the database init.sql the `license` table and related constraints
Remember to do that also in staging and prod databases

**Comment by MoeHome** [comment]
Should there be an info if the old license_id matches the new one?

**Comment by hugotiburtino** [comment]
IMHO it doesn't have to have an extra info about that but it could  return successfully early.

**Comment by MoeHome** [comment]
To specify: If an invalid user id isn't handled there will be an InternalServerError. We could change that to BadRequest.

**Comment by kulla** [comment]
> To specify: If an invalid user id isn't handled there will be an InternalServerError. We could change that to BadRequest.

Would be cool if it will be a bad request
