### ISSUE TITLE
EntityAddRevisionMutation: Do not save new revision when there have not been changes

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org-database-layer#225]
I guess the best to implement https://github.com/serlo/frontend/issues/1574 is in the DB layer since here it is the easiest to load the necessary fields. So: When there is no difference in the fields of the current revision with the new edit -> return `success === true` immediately

**Comment by hugotiburtino** [comment]
Somehow it is happening still. 
Reported by Anne. 

Steps to reproduce:
1. Go to a course (v.g. https://de.serlo-staging.dev/mathe/221124/%C3%BCberblick ) and chose Weitere Optionen -> Diese Kursseite -> überarbeiten
2.  Add a new course page, without changing anything, and save
3. Go to /entity/unrevised

**Comment by elbotho** [comment]
In 1. you mean "Weitere Optionen -> Gesamter Kurs -> Überarbeiten" right?

**Comment by kulla** [comment]
@hugotiburtino This is due to a change in how slate stores it's value: 
![2022-06-03-124322_1311x382_scrot](https://user-images.githubusercontent.com/1327215/171839434-4945a5ca-ce96-4c50-b386-109280c2aabc.png)
However I noticed the same error with other courses. I investigate it...

**Comment by hugotiburtino** [comment]
> @hugotiburtino This is due to a change in how slate stores it's value:

thanks for noticing that. 
For that specific case, we can't fix it in Backend.

@kulla when you're done if the investigation and if it doesn't have anything to do with DB layer, please close this issue and, if necessary, open one in another repo.

**Comment by kulla** [comment]
> @kulla when you're done if the investigation and if it doesn't have anything to do with DB layer, please close this issue and, if necessary, open one in another repo.

Okay, I have found the issue which is a new corner case: #285
