### ISSUE TITLE
[New Endpoint] PagesQuery

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/serlo.org-database-layer#241]
## Definition
It fetches from the database all static pages (possibly filtered by instance) and returns a collection of pages ids  (or possibly none) ,  

### Message (TypeScript definition)
```ts
interface Message {
  type: 'PagesQuery'
  payload: {
    instance?: string // filter for subdomain
  }
}
```

### Output (TypeScript definition)
```ts
interface Output {
  pages: number[]
}
```

## Description what happens in the database layer
Message is defined in `uuid/model/page/messages.rs`. All page ids are collected in the `page_respository` (by instance) and given back. 

## Necessary checks / possible errors
- [ ] It is optional to filter by `Instance` (if no instance is determined, then return all page ids)
- [ ] It returns an empty vector if no page is found for an instance (no error is thrown)

See https://github.com/serlo/api.serlo.org/issues/623

**Comment by MoeHome** [comment]
Should pages that are trashed also be returned?

**Comment by MoeHome** [comment]
> > Should pages that are trashed also be returned?
> 
> Do pages turn up in the recycle bin? If yes I would not return them here.

Pages are different from entities. So they aren't in DeletedEntities and I don't think they are in the recycle bin then.
