### ISSUE TITLE
Trigger `CreateEntityNotificationEvent` before `CheckoutRevisionNotificationEvent`

### ISSUE THREAD

**Issue by elbotho** [serlo/serlo.org-database-layer#270]
# What is wrong?

It seems currently in the event log it looks like entities that are created and accepted at the same time (by reviewers) are accepted before they are created.

**Comment by MoeHome** [comment]
I'm pretty sure this happens when the timestamps of the two events are the same. And then the sorting in the Query goes wrong.

**Comment by kulla** [comment]
> I'm pretty sure this happens when the timestamps of the two events are the same. And then the sorting in the Query goes wrong.

I guess [this](https://github.com/serlo/serlo.org-database-layer/pull/287) was the reason for the wrong ordering...
