### ISSUE TITLE
SetEntity… creates empty revision for parent

### ISSUE THREAD

**Issue by elbotho** [serlo/serlo.org-database-layer#271]
# What is wrong?

When editing an `ExerciseGroup` and only changing e.g. a solution of a `GroupedExercise` an empty revision of the `ExerciseGroup` is also created.
![image](https://user-images.githubusercontent.com/1258870/170816917-9fd8be25-355b-49a4-83b3-3faef2ba892e.png)

# How should it behave?

We should check if the parent changed before creating a new revision

**Comment by kulla** [comment]
Okay, I found the reason: We added a new field `cohesive` which is read as `false` when it is not present in the DB. So when a `ExerciseGroup` is saved which current is so old that it's current revision does not have a field `cohesive` a new revision with `cohesive === false` is stored. I work on a fix.
