### ISSUE TITLE
Review EntityType

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org-database-layer#34]
I implemented `EntityType` according to the ideas from #23. Furthermore, I also added some [fancy stuff](https://github.com/serlo/serlo.org-database-layer/blob/main/src/uuid/model/entity/abstract_entity.rs#L51) so that we can also pass an `EntityType` directly into a SQL query. Unfortunately, this includes some duplicated code since I couldn't find a way to "reverse" the rename stuff we do with serde. Maybe there is some easier way to do that.

**Comment by vroland** [comment]
Implement a macro (`macro_rules!` enough?), with https://doc.rust-lang.org/std/any/fn.type_name.html

**Comment by vroland** [comment]
Not quite a nice solution, but possible:
derive `Debug`, get the variant name with `format!{"{:?}", self)` and convert that to kebab case.

**Comment by inyono** [comment]
I decided to split up `EntityType` two types (one represents the value in the database, the other the serialized value in our JSON), see #72.
