### ISSUE TITLE
Add field for Metadata API: Keywords

### ISSUE THREAD

**Issue by CodingDive** [serlo/serlo.org-database-layer#383]
https://dini-ag-kim.github.io/amb/draft/#keywords

Ideally we'd optimize keywords for SEO e.g keywords that get searched for a lot

**Comment by hugotiburtino** [comment]
What kind of keywords do you have in mind? Like the title and taxonomies of the entity, v.g. 'addition', 'algebra', 'mathematics'?

**Comment by kulla** [comment]
> What kind of keywords do you have in mind? Like the title and taxonomies of the entity, v.g. 'addition', 'algebra', 'mathematics'?

Those we store in the database – it should be a parameter of the entity. Am I right?
