### ISSUE TITLE
POST /thread/set-archive

### ISSUE THREAD

**Issue by elbotho** [serlo/serlo.org-database-layer#46]
[Contract](https://pact.serlo.org/pacts/provider/serlo.org/consumer/api.serlo.org/latest#set_%22archived%22_state_of_a_thread_given_there_exists_a_thread_with_a_first_comment_with_an_id_of_100_and_user_with_id_1_is_authenticated)

**Comment by elbotho** [comment]
@inyono so here also just a simple `{ sucess: true }` response?

**Comment by inyono** [comment]
You can even return nothing here, status code is enoguh.
