### ISSUE TITLE
Maybe wrong EventType for set-uuid-state

### ISSUE THREAD

**Issue by elbotho** [serlo/serlo.org-database-layer#55]
https://github.com/serlo/serlo.org-database-layer/blob/21df42d5b5639bbe36ed663715211aa31ba06037/src/event/model/set_uuid_state.rs#L41

@inyono this should be `__typename: EventType::SetUuidState,` right?

**Comment by inyono** [comment]
Yes, good catch. (shouldn't cause issues atm since only `raw_typename` is actually used)

**Comment by elbotho** [comment]
Will fix it in my next PR,
was just hopeful thinking that the Event logic for /thread/set-archived is done already ^^
