### ISSUE TITLE
Add SubscriptionPayload

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org-database-layer#63]
We need a model for users to subscribe to uuids. The data structure of `subscription` is:

- `uuid_id` (the object the user subscribed to)
- `user_id` (the user that subscribed to the object)
- `notify_mailman` (whether the user wants to receive mails for that)
- `date` (the timestamp the object was subscribed to)

Apart from that, subscribing doesn't trigger any further stuff.

**Comment by elbotho** [comment]
Do we check if a equivalent relation exists at this point, or do we just delete all matching subscriptions on unsubscribing?

**Comment by inyono** [comment]
`(uuid_id, user_id)` has a `UNIQUE` constraint. So to be precise, this would have an "insert or update" semantic (where update doesn't trigger a date change). MySQL has a [`INSERT ON DUPLICATE KEY UPDATE`](https://www.mysqltutorial.org/mysql-insert-or-update-on-duplicate-key-update/) statement that appears to also work for `UNIQUE` constraints. If that doesn't work, deleting beforehand should also work fine :)

**Comment by elbotho** [comment]
@inyono I opted for `WHERE NOT EXISTS` because it does not screw with the table at all (auto increments) but feel free to change.
