### ISSUE TITLE
Add __typename to License

### ISSUE THREAD

**Issue by CarolinJaser** [serlo/serlo.org-database-layer#81]
Currently the payload for license is missing the __typename property.

It should probably be added here:
https://github.com/serlo/serlo.org-database-layer/blob/32685c5e053ca16d1d57322a6e60a39cc42080c6/src/license/model.rs#L10

**Comment by inyono** [comment]
This shouldn't be needed (correct me if I'm wrong). `__typename` was introduced for the "polymorphic" endpoints. E.g. both `uuid` and `notificationEvent` return one of many possible concrete types. So there has to be a way for GraphQL to distinguish between them. `license` on the other hand always returns a `License`.

**Comment by CarolinJaser** [comment]
Okay, that is interesting. Kulla and I found this while implementing the new Resover type helper in instance. @kulla do we need to re-think this? In addition I now do not get the same errors after I have updated my Mac. I am not entirely sure this is the problem

**Comment by CarolinJaser** [comment]
Sorry, my bad, we identified the problem correctly, but I should probably give some more context. So we found this when working with the Resolver for `InstanceAware`, since it is in a union with license. This causes a problem when implementing the new type helper for `InstanceAware`, because it expects `__typename` for both, but it is missing in `License`. Also, at the moment there is no GraphQl property, that receives `InstanceAware`, but in theory every Interface should be resolvable. In addition I think it would be better for consistency's sake to have `__typename` everywhere.

**Comment by inyono** [comment]
> This causes a problem when implementing the new type helper for `InstanceAware`, because it expects `__typename`, but it is missing in License.

Wait, why does `InstanceAware` contain `License`? This doesn't sound useful to me since the only field another instanceaware `AbstractUuid` shares with `License` is `id`. Since those ids don't have the same meaning (License is no UUID after all), an endpoint returning `InstanceAware` (including License) only makes sense over something like alias (which licenses don't have).

> In addition I think it would be better for consistency's sake to have __typename everywhere.

Don't have a strong opinion on that. We'd need to be more careful about type renamings then, though.

**Comment by CarolinJaser** [comment]
Yeah, that is a good question. @kulla, do you have an answer to this?

**Comment by CarolinJaser** [comment]
As per suggestion of @inyono, I removed InstanceAware for License instead. Closing the issue.
